services:
  db:
    image: mysql:8
    container_name: mysql-api
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wiseai
      MYSQL_USER: jmh
      MYSQL_PASSWORD: jmh
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    
  app:
    build: .
    container_name: reservation-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/wiseai
      SPRING_DATASOURCE_USERNAME: jmh
      SPRING_DATASOURCE_PASSWORD: jmh
    depends_on:
      - db
      
volumes:
  mysql-data: